// <auto-generated />
using System;
using AnimeOverseer.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeOverseer.Server.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    partial class AnimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("AnimeOverseer.Server.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AniListId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Episodes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEnglishTitle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KitsuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MALId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferredImageId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId", "Source", "Type", "ImageUrl")
                        .IsUnique();

                    b.ToTable("AnimeImages");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeTitleAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId", "Title")
                        .IsUnique();

                    b.ToTable("AnimeTitleAliases");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeDemographic", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemographicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimeId", "DemographicId");

                    b.HasIndex("DemographicId");

                    b.ToTable("AnimeDemographics");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimeId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimeGenres");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeTheme", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimeId", "ThemeId");

                    b.HasIndex("ThemeId");

                    b.ToTable("AnimeThemes");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.IntegrationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndAfterOccurrences")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastQueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthlyMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NthWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueuedOccurrences")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weekday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeekdaysJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IntegrationSchedules");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.CachedAnimeRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RelatedMalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RootMalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CachedAnimeRelations");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Demographic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Demographics");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.SyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncedAnimeIds")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.SyncJobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncJobLogs");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Anime", b =>
                {
                    b.HasOne("AnimeOverseer.Server.Models.Season", "Season")
                        .WithMany("Animes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeImage", b =>
                {
                    b.HasOne("AnimeOverseer.Server.Models.Anime", "Anime")
                        .WithMany("Images")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeTitleAlias", b =>
                {
                    b.HasOne("AnimeOverseer.Server.Models.Anime", "Anime")
                        .WithMany("TitleAliases")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeDemographic", b =>
                {
                    b.HasOne("AnimeOverseer.Server.Models.Anime", "Anime")
                        .WithMany("AnimeDemographics")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeOverseer.Server.Models.Demographic", "Demographic")
                        .WithMany("AnimeDemographics")
                        .HasForeignKey("DemographicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Demographic");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeGenre", b =>
                {
                    b.HasOne("AnimeOverseer.Server.Models.Anime", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeOverseer.Server.Models.Genre", "Genre")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.AnimeTheme", b =>
                {
                    b.HasOne("AnimeOverseer.Server.Models.Anime", "Anime")
                        .WithMany("AnimeThemes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeOverseer.Server.Models.Theme", "Theme")
                        .WithMany("AnimeThemes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Request", b =>
                {
                    b.HasOne("AnimeOverseer.Server.Models.Anime", null)
                        .WithMany("Requests")
                        .HasForeignKey("AnimeId");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Anime", b =>
                {
                    b.Navigation("AnimeDemographics");

                    b.Navigation("AnimeGenres");

                    b.Navigation("Images");

                    b.Navigation("TitleAliases");

                    b.Navigation("AnimeThemes");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Demographic", b =>
                {
                    b.Navigation("AnimeDemographics");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Genre", b =>
                {
                    b.Navigation("AnimeGenres");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Season", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("AnimeOverseer.Server.Models.Theme", b =>
                {
                    b.Navigation("AnimeThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
